classic1.so: $(ONE_D_CLASSIC_SOURCES) $(RP_SOURCE)
	${F2PY} -m classic1 -c $^

classic1fw.so: $(ONE_D_CLASSIC_FWAVE_SOURCES) $(RP_SOURCE)
	${F2PY} -m classic1fw -c $^

classicimplicit1.so: $(ONE_D_CLASSIC_IMPLICIT_SOURCES) $(RP_SOURCE)
	${F2PY} -m classicimplicit1 -c $^

sharpclaw1.so: $(ONE_D_SHARPCLAW_SOURCES) $(RP_SOURCE)
	${F2PY} -m sharpclaw1 -c $(ONE_D_SHARPCLAW_SOURCES) $(RP_SOURCE)

classic2.so: $(TWO_D_CLASSIC_SOURCES) $(RP_SOURCE) 
	${F2PY} -m classic2 -c $(TWO_D_CLASSIC_SOURCES) $(RP_SOURCE) 	

classic2fw.so: $(TWO_D_CLASSIC_FWAVE_SOURCES) $(RP_SOURCE)
	${F2PY} -m classic2fw -c $^

sharpclaw2.so: $(TWO_D_SHARPCLAW_SOURCES) $(RP_SOURCE) 
	${F2PY} -m sharpclaw2 -c $(TWO_D_SHARPCLAW_SOURCES) $(RP_SOURCE) 

step2ds.o: $(TWO_D_CLASSIC)/step2ds.f
	$(FC) $(FFLAGS) -o step2ds.o -c $(TWO_D_CLASSIC)/step2ds.f

classic3.so: $(THREE_D_CLASSIC_SOURCES) $(RP_SOURCE) 
	${F2PY} -m classic3 -c $(THREE_D_CLASSIC_SOURCES) $(RP_SOURCE) 	

flux2.o: $(TWO_D_CLASSIC)/flux2.f
	$(FC) $(FFLAGS) -o flux2.o -c $(TWO_D_CLASSIC)/flux2.f

flux2fw.o: $(TWO_D_CLASSIC)/flux2fw.f
	$(FC) $(FFLAGS) -o flux2fw.o -c $(TWO_D_CLASSIC)/flux2fw.f

flux3.o: $(THREE_D_CLASSIC)/flux3.f
	$(FC) $(FFLAGS) -o flux3.o -c $(THREE_D_CLASSIC)/flux3.f

limiter.o: $(ONE_D_CLASSIC)/limiter.f
	$(FC) $(FFLAGS) -o limiter.o -c $(ONE_D_CLASSIC)/limiter.f

philim.o: $(ONE_D_CLASSIC)/philim.f
	$(FC) $(FFLAGS) -o philim.o -c $(ONE_D_CLASSIC)/philim.f

clean:
	rm -f *.o *.so *.pyc *.log

clobber: clean
	rm -rf _output/
	rm -rf _plots/
