PYCLAWMAKE = $(PYCLAW)/Makefile.common

RP_SOURCE =   $(RIEMANN)/src/rpn2_shallow_roe-with-efix.f95 $(RIEMANN)/src/rpt2_shallow_roe-with-efix.f95 

all: classic2.so sharpclaw2.so

include $(PYCLAWMAKE)

