PYCLAWMAKE = $(PYCLAW)/Makefile.common

FC ?= gfortran

RP_SOURCE =   $(RIEMANN)/src/rpn2_advection_annulus.f $(RIEMANN)/src/rpt2_advection_annulus.f

all: classic2.so sharpclaw2.so

include $(PYCLAWMAKE)
