PYCLAWMAKE = $(PYCLAW)/Makefile.common

RP_SOURCE =   $(RIEMANN)/src/rpn3_vc_acoustics.f90 $(RIEMANN)/src/rpt3_vc_acoustics.f90 $(RIEMANN)/src/rptt3_vc_acoustics.f90

all: classic3.so

include $(PYCLAWMAKE)

