PYCLAWMAKE = $(PYCLAW)/Makefile.common

RP_SOURCE =   $(RIEMANN)/src/rpn3_vc_acoustics.f $(RIEMANN)/src/rpt3_vc_acoustics.f $(RIEMANN)/src/rptt3_vc_acoustics.f

all: classic3.so

include $(PYCLAWMAKE)

