PYCLAWMAKE = $(PYCLAW)/Makefile.common

RP_SOURCE =   $(RIEMANN)/src/rpn2_euler_5wave.f $(RIEMANN)/src/rpt2_euler_5wave.f
SRCTERM_SOURCE = src2.f
all: classic2.so sharpclaw2.so

include $(PYCLAWMAKE)

