name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
      
defaults:
  run:
    shell: bash

jobs:
  build-linux:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: install clawpack
    - run: git clone --branch=master --depth=100 --quiet git://github.com/clawpack/clawpack
      run: cd clawpack
      run: git submodule init
      run: git submodule update clawutil visclaw riemann
      # remove master branch of pyclaw and use branch we're testing
      run: rm -rf pyclaw
      run: ln -s ../ pyclaw
      run: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies and compile
      run: conda env update --file environment.yml --name base
      run: python setup.py install
    - name: Test
      run: cd pyclaw
      run: bash ./run_tests_on_travis.sh
      run: coveralls
