name: Test PyClaw

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

permissions:
  contents: read

env:
  CLAW: ${{ github.workspace }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gfortran

        python -m pip install --upgrade pip
        pip install 'numpy<2.0'
        pip install matplotlib #Some imports require matplotlib
        pip install scipy #To not skip tests
        pip install flake8 meson-python ninja pytest coveralls
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Checkout Clawpack
      uses: actions/checkout@v4.1.5
      with:
        repository: clawpack/clawpack
        submodules: true

    - name: Checkout PyClaw branch
      uses: actions/checkout@v4.1.5
      with:
        path: pyclaw
    
    - name: Install clawpack
      run: |
        cd ${CLAW}
        pip install --no-build-isolation --editable .

    - name: Test with pytest
      run: |
        cd ${CLAW}/pyclaw
        coverage run --source=src -m pytest --ignore=development -k "not test_shallow_sphere"

    - name: Upload to Coveralls
      if: always()
      run: |
        cd ${CLAW}/pyclaw
        ls -l .coverage
        coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
